name: Build OpenWrt

on: [push,repository_dispatch,workflow_dispatch]

jobs:
  BUILD:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Initialization 
        shell: bash
        run: | 
          echo "Get time for release-tag-name"
          echo "RELEASE_TAG_NAME=$(date +'%Y%m%d')" >> $GITHUB_ENV 
          echo "\n\n\nDo things about apt"
          sudo apt-get update
          sudo apt-get install -y $(cat initialization.packages)
          echo "\n\n\nDo things about git"
          git clone https://github.com/coolsnowwolf/lede openwrt
          echo "\n\n\nDo things about myconfig"
          mv config_file openwrt/.config
          echo "\n\n\nDo things about feeds"
          cd openwrt && ./scripts/feeds update -a && ./scripts/feeds install -a && make download -j$(nproc)
      - name: Build
        shell: bash
        run: |
          cd openwrt
          make defconfig
          make -j$(nproc) || make -j1 || make -j1 V=s || echo "STATUS=BAD" >> $GITHUB_ENV
          cd bin/targets/*/* && rm -rf packages && echo "FIRMWARE=$PWD" >> $GITHUB_ENV && echo "STATUS=OK" >> $GITHUB_ENV
      - name: Upload
        if: env.STATUS == 'OK'
        uses: softprops/action-gh-release@v1 
        with:
          tag_name: ${{ env.RELEASE_TAG_NAME }}
          body_path: README.md
          token: ${{ secrets.GH_TOKEN }}
          files: ${{ env.FIRMWARE }}/*



